#! /usr/bin python

#------------------------------------------------------------------------------
# PROGRAM: iris-plt.py --> Iris 3.1 only code using Matplotlib to plot
#------------------------------------------------------------------------------
# Version 0.1
# 5 March, 2021
# Satyaban Bishoyi Ratna & Michael Taylor
# s DOT bishoyi-ratna AT uea DOT ac DOT uk
# michael DOT a DOT taylor AT uea DOT ac DOT uk 
#------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------------
# IMPORT PYTHON LIBRARIES
# ---------------------------------------------------------------------------------------------------------

import numpy as np
import iris.analysis
import iris.plot as iplt
import matplotlib
import matplotlib.pyplot as plt

# Silence library version change notifications
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)
matplotlib.rcParams['mpl_toolkits.legacy_colorbar'] = False

# ---------------------------------------------------------------------------------------------------------
# SETTINGS
# ---------------------------------------------------------------------------------------------------------

datacube1 = 'DATA/tas_hadukgrid_uk_1km.nc'
datacube2 = 'DATA/tas_rcp85_land-cpm_uk_2.2km.nc'
datacube3 = 'DATA/tas_rcp85_land-rcm_uk_12km.nc'

# Plot settings:
cmap = 'brewer_YlOrRd_09'
fontsize = 12
levels = np.arange(-4, 14, 0.5)
x0 = -0.60; x1 = 0.70; # London region extent (longitude)
y0 = 51.10; y1 = 51.85 # London region extent (latitude)

# Runtime flags (True / False):
plot_uk_iplt = True # True --> same as London_plot_comp.png (generated by London_plot_comp.py)

# ---------------------------------------------------------------------------------------------------------
# LOAD: Iris datacubes and define regridded datasets 
# ---------------------------------------------------------------------------------------------------------

print('loading Iris datacubes ...')

hadk = iris.load(datacube1)
cpm = iris.load(datacube2)
rcm = iris.load(datacube3)

print('regridding Iris datacubes ...')

hadkcpm = hadk[0].regrid(cpm[1], iris.analysis.Linear())
rcmcpm = rcm[1].regrid(cpm[1], iris.analysis.Linear())
data1 = hadkcpm[0,:,:]
data2 = cpm[1][0,0,:,:]
data3 = rcmcpm[0,0,:,:]

# ---------------------------------------------------------------------------------------------------------
# PLOT: using iplt
# ---------------------------------------------------------------------------------------------------------

if plot_uk_iplt == True:

    print('generating Iris contour plot ...')

    figstr = 'ukcp18-iplt.png'

    plt.figure(figsize=(10,10))
    plt.subplot(1, 3, 1)
    fig1 = iplt.contourf(data1, levels, cmap=cmap); plt.title('HadUK', fontsize=fontsize)
    ax1 = plt.gca(); ax1.coastlines(resolution='50m')
    plt.subplot(1, 3, 2)
    fig2 = iplt.contourf(data2, levels, cmap=cmap); plt.title('CPM', fontsize=fontsize)
    ax2 = plt.gca(); ax2.coastlines(resolution='50m')
    plt.subplot(1, 3, 3)
    fig3 = iplt.contourf(data3, levels, cmap=cmap); plt.title('RCM', fontsize=fontsize)
    ax3 = plt.gca(); ax3.coastlines(resolution='50m')
    plt.colorbar(orientation='horizontal')
    plt.savefig(figstr)

# ------------------------------------------------------------------------------------------------------------------
print('** END')

