#! /usr/bin python

#------------------------------------------------------------------------------
# PROGRAM: iris-xarray-cartopy.py
#------------------------------------------------------------------------------
# Version 0.2
# 4 March, 2021
# Satyaban Bishoyi Ratna & Michael Taylor
# s DOT bishoyi-ratna AT uea DOT ac DOT uk
# michael DOT a DOT taylor AT uea DOT ac DOT uk 
#------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------------
# IMPORT PYTHON LIBRARIES
# ---------------------------------------------------------------------------------------------------------

import numpy as np
import xarray as xr
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import AxesGrid
import iris.analysis
import iris.plot as iplt
import cartopy.crs as ccrs
import cartopy.feature as cf
#from cartopy.io import shapereader
#from cartopy.util import add_cyclic_point
#from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
#from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER

# Silence library version change notifications
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)
matplotlib.rcParams['mpl_toolkits.legacy_colorbar'] = False

# ---------------------------------------------------------------------------------------------------------
# SETTINGS
# ---------------------------------------------------------------------------------------------------------

datacube1 = 'DATA/tas_hadukgrid_uk_1km.nc'
datacube2 = 'DATA/tas_rcp85_land-cpm_uk_2.2km.nc'
datacube3 = 'DATA/tas_rcp85_land-rcm_uk_12km.nc'

# Plot settings:
cmap = 'brewer_YlOrRd_09'
fontsize = 12
levels = np.arange(-4, 14, 0.5)
x0 = -0.60; x1 = 0.70; # London region extent (longitude)
y0 = 51.10; y1 = 51.85 # London region extent (latitude)

# Runtime flags (True / False):
plot_uk_iplt = False # True --> same as London_plot_comp.png (generated by London_plot_comp.py)
plot_uk_xarray = True
plot_london_cartopy = True

# ---------------------------------------------------------------------------------------------------------
# LOAD: Iris datacubes and define regridded datasets 
# ---------------------------------------------------------------------------------------------------------

print('loading Iris datacubes ...')

hadk = iris.load(datacube1)
cpm = iris.load(datacube2)
rcm = iris.load(datacube3)

print('regridding Iris datacubes ...')

hadkcpm = hadk[0].regrid(cpm[1], iris.analysis.Linear())
rcmcpm = rcm[1].regrid(cpm[1], iris.analysis.Linear())
data1 = hadkcpm[0,:,:]
data2 = cpm[1][0,0,:,:]
data3 = rcmcpm[0,0,:,:]

# ---------------------------------------------------------------------------------------------------------
# METHODS
# ---------------------------------------------------------------------------------------------------------

def convert_OSGB_PlateCarree(datacube):

    # Function to convert Iris coordinates from OSGB to PlateCarree and return lon, lat and values

    proj_x = xr.DataArray.from_iris(datacube).grid_longitude
    proj_y = xr.DataArray.from_iris(datacube).grid_latitude
    xx, yy = np.meshgrid(proj_x, proj_y)
    coord_native_cartopy = datacube.coord_system().as_cartopy_projection()
    coord_system_target = iris.coord_systems.GeogCS(iris.analysis.cartography.DEFAULT_SPHERICAL_EARTH_RADIUS)
    coord_target_cartopy = coord_system_target.as_cartopy_projection()
    lon, lat, _ = coord_target_cartopy.transform_points(coord_native_cartopy, xx, yy).T
    lon = lon.T
    lat = lat.T
    val = xr.DataArray.from_iris(datacube).values[:,:]

    return lon, lat, val

def plot_cartopy(lon,lat,val,levels,cmap,fontsize,titlestr,figstr):

    # Generic cartopy contour plotting function

    print('generating Cartopy contour plot ...')

    fig  = plt.figure(figsize=(10,10))
    ax = plt.axes(projection=ccrs.PlateCarree())
    cp = plt.contourf(lon, lat, val, levels, transform=ccrs.PlateCarree(), zorder=0, alpha=0.65, cmap=cmap)        
    cb = plt.colorbar(cp, orientation="vertical", shrink=0.5, pad=0.05)            
    ax.add_feature(cf.LAND)        
    ax.add_feature(cf.OCEAN)        
    ax.add_feature(cf.COASTLINE)        
    ax.add_feature(cf.BORDERS, linestyle=':')        
    ax.set_extent([x0, x1, y0, y1])        
    plt.title(titlestr, fontsize=fontsize)        
    plt.savefig(figstr)

# ---------------------------------------------------------------------------------------------------------
# PLOTS
# ---------------------------------------------------------------------------------------------------------

if plot_uk_iplt == True:

    print('generating Iris contour plot ...')

    figstr = 'ukcp18-iplt.png'

    plt.figure(figsize=(10,10))
    plt.subplot(1, 3, 1)
    fig1 = iplt.contourf(data1, levels, cmap=cmap); plt.title('HadUK', fontsize=fontsize)
    ax1 = plt.gca(); ax1.coastlines(resolution='50m')
    plt.subplot(1, 3, 2)
    fig2 = iplt.contourf(data2, levels, cmap=cmap); plt.title('CPM', fontsize=fontsize)
    ax2 = plt.gca(); ax2.coastlines(resolution='50m')
    plt.subplot(1, 3, 3)
    fig3 = iplt.contourf(data3, levels, cmap=cmap); plt.title('RCM', fontsize=fontsize)
    ax3 = plt.gca(); ax3.coastlines(resolution='50m')
    plt.colorbar(orientation='horizontal')
    plt.savefig(figstr)

if plot_uk_xarray == True:

    print('generating Matplotlib Xarray contour plot ...')

    figstr = 'ukcp18-xarray.png'

    fig = plt.figure(figsize=(10, 10))
    grid = AxesGrid(fig, 111, nrows_ncols=(1, 3),
                    axes_pad=0.05,
                    cbar_mode='single', cbar_location='right', cbar_pad=0.1)
    j=0
    for ax in grid:
        ax.set_axis_off()
        if j == 0:
            fig1 = ax.contourf(xr.DataArray.from_iris(data1).values[:,:], levels, cmap=cmap)
            ax.set_title('HadUK', fontsize=fontsize)
        elif j == 1:
            fig2 = ax.contourf(xr.DataArray.from_iris(data2).values[:,:], levels, cmap=cmap)
            ax.set_title('CPM', fontsize=fontsize)
        elif j == 2:
            fig3 = ax.contourf(xr.DataArray.from_iris(data3).values[:,:], levels, cmap=cmap)
            ax.set_title('RCM', fontsize=fontsize)
        j += 1
    cbar = ax.cax.colorbar(fig3)
    plt.savefig(figstr)

if plot_london_cartopy == True:

    print('converting coords from OSGV to PlateCarree ...')
    lon, lat, val = convert_OSGB_PlateCarree(data1)

    titlestr = 'HadUK'; figstr = 'PLOTS/ukcp18-london-cartopy-hadkcpm.png'
    plot_cartopy(lon,lat,val,levels,cmap,fontsize,titlestr,figstr)

    print('converting coords from OSGV to PlateCarree ...')
    lon, lat, val = convert_OSGB_PlateCarree(data2)

    titlestr = 'CPM'; figstr = 'PLOTS/ukcp18-london-cartopy-cpm.png'
    plot_cartopy(lon,lat,val,levels,cmap,fontsize,titlestr,figstr)

    print('converting coords from OSGV to PlateCarree ...')
    lon, lat, val = convert_OSGB_PlateCarree(data3)

    titlestr = 'RCM'; figstr = 'PLOTS/ukcp18-london-cartopy-rcm.png'
    plot_cartopy(lon,lat,val,levels,cmap,fontsize,titlestr,figstr)

# ------------------------------------------------------------------------------------------------------------------
print('** END')

